### ISSUE TITLE
【TODO】developer-plus TS启动模版

### ISSUE THREAD

**Issue by alexzhang1030** [developer-plus/ToDoList#12]
### 描述

需要建设一个 ts-starter 启动模版，包括但不限于以下内容：
- lint
- build
- 合理完善的 tsconfig
- pnpm-monorepo
- gitignore

欢迎你的奇思妙想

### 目标仓库

https://github.com/developer-plus/starter-ts
### 截止日期

2022-05-17

### 其他补充

暂无

**Comment by alexzhang1030** [comment]
此任务已有人接

**Comment by Hongbusi** [comment]
starter-ts 听起来更好哎

**Comment by alexzhang1030** [comment]
> starter-ts 听起来更好哎

改了改了

**Comment by chris-zhu** [comment]
> 此任务已有人接

如果有人接任务，可以分配个Assignees。

**Comment by alexzhang1030** [comment]
很尴尬，接的人不在组织中

> > 此任务已有人接
> 
> 如果有人接任务，可以分配个 Assignees。

**Comment by alexzhang1030** [comment]
> > 此任务已有人接
> 
> 如果有人接任务，可以分配个 Assignees。

欢迎大佬呀
